services:
  - type: web
    name: pharo-fantasy
    runtime: docker
    plan: free
    envVars:
      - key: AUTH_SECRET
        generateValue: true
      - key: ADMIN_INITIAL_PASSWORD
        sync: false
    disk:
      name: pharo-data
      mountPath: /data
      sizeGB: 1
